#include "peripheral_init.h"
#include "stm32c031xx.h"
#include "SDK_gpio.h"
#include "SDK_pwm.h"
#include "stm32c0xx_ll_adc.h"
#include "SDK_adc.h"
#include "SDK_spi.h"
//#include "SDK_pwm.h"

void InitializePeripherals(void) {
  // Initialize all GPIO pins to a default state
  SDK_GPIO_Init();

  //SDK_EXTI_ConfigPin(GPIOA, LL_GPIO_PIN_3, LL_GPIO_MODE_INPUT, LL_GPIO_PULL_NO, LL_EXTI_TRIGGER_RISING_FALLING, EXTI2_3_IRQn,
  //                        LL_EXTI_CONFIG_PORTA, LL_EXTI_LINE_3, LL_EXTI_CONFIG_LINE3);

  SDK_EXTI_ConfigPin(GPIOB, LL_GPIO_PIN_5, LL_GPIO_MODE_INPUT, LL_GPIO_PULL_NO, LL_EXTI_TRIGGER_RISING_FALLING, EXTI4_15_IRQn,
                            LL_EXTI_CONFIG_PORTB, LL_EXTI_LINE_5, LL_EXTI_CONFIG_LINE5);

  SDK_GPIO_ConfigPin(GPIOA, LL_GPIO_PIN_4, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOA, LL_GPIO_PIN_6, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOA, LL_GPIO_PIN_7, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOA, LL_GPIO_PIN_8, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOA, LL_GPIO_PIN_12, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOA, LL_GPIO_PIN_15, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);

  SDK_GPIO_WritePin(GPIOA, LL_GPIO_PIN_4, GPIO_PIN_HIGH);
  SDK_GPIO_WritePin(GPIOA, LL_GPIO_PIN_6, GPIO_PIN_HIGH);
  SDK_GPIO_WritePin(GPIOA, LL_GPIO_PIN_7, GPIO_PIN_LOW);
  SDK_GPIO_WritePin(GPIOA, LL_GPIO_PIN_8, GPIO_PIN_LOW);
  SDK_GPIO_WritePin(GPIOA, LL_GPIO_PIN_12, GPIO_PIN_LOW);
  SDK_GPIO_WritePin(GPIOA, LL_GPIO_PIN_15, GPIO_PIN_HIGH);

  SDK_GPIO_ConfigPin(GPIOB, LL_GPIO_PIN_0, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOB, LL_GPIO_PIN_1, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOB, LL_GPIO_PIN_3, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
  SDK_GPIO_ConfigPin(GPIOB, LL_GPIO_PIN_4, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL);
 // SDK_GPIO_ConfigPin(GPIOB, LL_GPIO_PIN_8, LL_GPIO_MODE_OUTPUT, LL_GPIO_PULL_NO, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_OUTPUT_PUSHPULL); // ToDo: Debugging

  SDK_GPIO_WritePin(GPIOB, LL_GPIO_PIN_0, GPIO_PIN_LOW);
  SDK_GPIO_WritePin(GPIOB, LL_GPIO_PIN_1, GPIO_PIN_LOW);
  SDK_GPIO_WritePin(GPIOB, LL_GPIO_PIN_3, GPIO_PIN_LOW);
  SDK_GPIO_WritePin(GPIOB, LL_GPIO_PIN_4, GPIO_PIN_HIGH);

  SDK_ADC_ChannelConfig channels[] = {
      {LL_ADC_CHANNEL_0, LL_ADC_SAMPLINGTIME_19CYCLES_5}, // VBAT
      {LL_ADC_CHANNEL_3, LL_ADC_SAMPLINGTIME_19CYCLES_5}, // VUSB
	  {LL_ADC_CHANNEL_11, LL_ADC_SAMPLINGTIME_19CYCLES_5}, // VSYS
	  {LL_ADC_CHANNEL_TEMPSENSOR, LL_ADC_SAMPLINGTIME_160CYCLES_5},
	  {LL_ADC_CHANNEL_VREFINT, LL_ADC_SAMPLINGTIME_79CYCLES_5},
  };
  SDK_ADC_InitInterruptMode(channels, (sizeof(channels) / sizeof(SDK_ADC_ChannelConfig)));

  SDK_SPI_Init();
  SDK_PWM_Init();
}
